---
- name: Install Shadowsocks dependencies
  apt: pkg={{ item }}
  with_items:
    - python-gevent
    - python-m2crypto
    - python-pip
    - qrencode

- name: Add the Shadowsocks user
  user: name=shadowsocks
        home=/home/shadowsocks
        shell=/usr/sbin/nologin
        comment="Shadowsocks User"

- name: Install Shadowsocks
  pip: name=shadowsocks

- name: Generate Shadowsocks config file
  template: src=config.json.j2
            dest=/home/shadowsocks/config.json
            owner=shadowsocks
            group=shadowsocks
            mode=640

- name: Copy Shadowsocks init script
  copy: src=shadowsocks-init
        dest=/etc/init.d/shadowsocks
        owner=root
        group=root
        mode=755

- name: Enable the Shadowsocks init script so the service will start at boot
  command: update-rc.d shadowsocks defaults
           creates=/etc/rc0.d/K20shadowsocks

- name: Start Shadowsocks
  service: name=shadowsocks
           state=started

- name: Generate the Shadowsocks QR code
  # The ss:// URI format is documented here:
  #   http://shadowsocks.org/1.4/config/quick-guide.html
  shell: echo -n '{{ shadowsocks_encryption_method }}:{{ shadowsocks_password }}@{{ ansible_default_ipv4.address }}:{{ shadowsocks_server_port }}' | base64 | sed 's/^/ss:\/\//' | qrencode -s 15 -o ss.png
         chdir=/home/shadowsocks

- name: Set permissions on the QR code image
  file: path=/home/shadowsocks/ss.png
        owner=shadowsocks
        group=shadowsocks
        mode=640

- name: Fetch the QR code image
  fetch: dest=/tmp/shadowsocks-qr-code/
         src=/home/shadowsocks/ss.png
         flat=yes

- name: Pause for explanation
  pause: prompt="A custom QR code that can be used to automatically configure your Shadowsocks clients has been downloaded to /tmp/shadowsocks-qr-code/ss.png. Simply scan this image to get up and running quickly. Look for the option when creating a new profile in the iOS and Android applications. Press any key to continue..."
